### ISSUE TITLE
asking for roots password

### ISSUE THREAD

**Issue by AtulTakekarManulife** [adejoux/kitchen-wpar#16]
When I ran kitchen create with this configuration in kitchen.yml

```
driver:
  name: wpar
  aix_host: localhost
  aix_user: root
  wpar_address: 10.10.10.10
  share_network_resolution: true
```

Kitchen is asking for password for root user
```
(base) macC02DFGDSS:aix takeatu$ kitchen create
-----> Starting Test Kitchen (v3.0.0)
-----> Creating <default-wpar>...
/Users/takeatu/.chefdk/gem/ruby/3.0.0/gems/kitchen-wpar-0.4.4/lib/kitchen/driver/wpar.rb:228:in `ssh_command': Passing nil, or [nil] to Net::SSH.start is deprecated for keys: keys
root@localhost's password:
```
